In [2]:
import numpy as np
array=([
    [1,3,7,9],
    [4,6,8,12],
    [7,5,3,7],
    [5,5,8,8]
])
array_sort=np.sort(array, axis=0)
array_t=np.transpose(array_sort)
print('отсортированные столбцы \n', array_sort )
print('транспорированный массив от отсортированного \n', array_t)
print('обьединенное вертикально \n', np.vstack((array_sort,array_t)))
print('обьединенные горизонтально \n', np.hstack((array_sort,array_t)))
print('обьединенные без осей \n', np.concatenate((array_sort, array_t), axis=None))

отсортированные столбцы 
 [[ 1  3  3  7]
 [ 4  5  7  8]
 [ 5  5  8  9]
 [ 7  6  8 12]]
транспорированный массив от отсортированного 
 [[ 1  4  5  7]
 [ 3  5  5  6]
 [ 3  7  8  8]
 [ 7  8  9 12]]
обьединенное вертикально 
 [[ 1  3  3  7]
 [ 4  5  7  8]
 [ 5  5  8  9]
 [ 7  6  8 12]
 [ 1  4  5  7]
 [ 3  5  5  6]
 [ 3  7  8  8]
 [ 7  8  9 12]]
обьединенные горизонтально 
 [[ 1  3  3  7  1  4  5  7]
 [ 4  5  7  8  3  5  5  6]
 [ 5  5  8  9  3  7  8  8]
 [ 7  6  8 12  7  8  9 12]]
обьединенные без осей 
 [ 1  3  3  7  4  5  7  8  5  5  8  9  7  6  8 12  1  4  5  7  3  5  5  6
  3  7  8  8  7  8  9 12]


In [ ]:
import numpy as np
import math as m
def type_def(a):
    if np.amin(a) < 0:
        if abs(np.amax(a)) < abs(np.amin(a)):
            eltype=m.ceil(np.log(abs(np.amin(a)))/np.log(2))
        else:
            eltype=m.ceil(np.log(np.amax(a))/np.log(2))
        dtype=np.int8
    else:
        eltype=m.ceil(np.log(np.amax(a))/np.log(2))
        if eltype<11:
            dtype=np.uint8
        else:
            dtype=np.uint64
    return dtype

n=int(input())
a=[]
nums=[0,n]
for i in nums:
    a.append(int(input()))
dtype=type_def(a)
array = np.array(a, dtype=dtype)
print(array)